name: test

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo test
